#!/bin/bash

set -x

CMD=$1
shift
ARGS=$@

dev() {
  local WEBPACK=node_modules/webpack/bin/webpack.js
  local WEBPACK_DEV_SERVER=node_modules/webpack-dev-server/bin/webpack-dev-server.js
  trap 'kill $(jobs -p)' EXIT
  $WEBPACK -w &
  $WEBPACK_DEV_SERVER --hot --inline --host 0.0.0.0 --port 8008 --content-base public/ &
  wait
}

build() {
 WEBPACK=node_modules/webpack/bin/webpack.js

 npm install babel-core
 npm install
 $WEBPACK -p


}

deploy() {
	docker pull xueshanf/awscli
	docker run --rm \
	 -e AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID \
	 -e AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY \
	 -e AWS_DEFAULT_REGION=us-east-1 \
	 -v $PWD:/app xueshanf/awscli\
		aws s3 cp \
			--cache-control "max-age=3600" \
			./public \
			s3://soundboard.alexjpaz.com
}

dockerBuild() {
  local CIDFILE=$(mktemp /tmp/cidfile.XXXXXXXXXX)
  rm $CIDFILE
	docker build -t alexjpaz/soundboard-client-web .
	docker run --cidfile $CIDFILE alexjpaz/soundboard-client-web echo starting container
	docker cp $(cat $CIDFILE):/usr/src/app/public ./public
}

runTest() {
  local TESTRUNNER=node_modules/mocha/bin/mocha
  $TESTRUNNER --recursive $ARGS
}

$CMD $ARGS
